CREATE TABLE Applicants(
   Application_ID   INTEGER  NOT NULL PRIMARY KEY 
  ,Applicant_ID     INTEGER  NOT NULL
  ,Name             VARCHAR(39) NOT NULL
  ,Inventor         VARCHAR(39) NOT NULL
  ,Applicant_Status VARCHAR(10) NOT NULL
);
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249801,160000,'3 Round Stones, Inc.','3 Round Stones, Inc.','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249802,160001,'48 Factoring Inc.','48 Factoring Inc.','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249803,160002,'5PSolutions','5PSolutions','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249804,160003,'Abt Associates','Abt Associates','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249805,160004,'Accela','Accela','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249806,160005,'Accenture','Accenture','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249807,160006,'AccuWeather','AccuWeather','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249808,160007,'Acxiom','Acxiom','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249809,160008,'Adaptive','Adaptive','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249810,160009,'Adobe Digital Government','Adobe Digital Government','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249811,160010,'Aidin','Aidin','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249812,160011,'Alarm.com','Alarm.com','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249813,160012,'Allianz','Allianz','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249814,160013,'Allied Van Lines','Allied Van Lines','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249815,160014,'AllState Insurance Group','AllState Insurance Group','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249816,160015,'Alltuition','Alltuition','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249817,160016,'Altova','Altova','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249818,160017,'Amazon Web Services','Amazon Web Services','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249819,160018,'American Red Ball Movers','American Red Ball Movers','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249820,160019,'Amida Technology Solutions','Amida Technology Solutions','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249821,160020,'Analytica','Analytica','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249822,160021,'Apextech LLC','Apextech LLC','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249823,160022,'Appallicious','Appallicious','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249824,160023,'Aquicore','Aquicore','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249825,160024,'Archimedes Inc.','Archimedes Inc.','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249826,160025,'AreaVibes Inc.','AreaVibes Inc.','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249827,160026,'Arpin Van Lines','Arpin Van Lines','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249828,160027,'Arrive Labs','Arrive Labs','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249829,160028,'ASC Partners','ASC Partners','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249830,160029,'Asset4','Asset4','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249831,160030,'Atlas Van Lines','Atlas Van Lines','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249832,160031,'AtSite','AtSite','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249833,160032,'Aunt Bertha, Inc.','Aunt Bertha, Inc.','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249834,160033,'Aureus Sciences (*Now part of Elsevier)','Aureus Sciences (*Now part of Elsevier)','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249835,160034,'AutoGrid Systems','AutoGrid Systems','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249836,160035,'Avalara','Avalara','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249837,160036,'Avvo','Avvo','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249838,160037,'Ayasdi','Ayasdi','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249839,160038,'Azavea','Azavea','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249840,160039,'BaleFire Global','BaleFire Global','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249841,160040,'Barchart','Barchart','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249842,160041,'Be Informed','Be Informed','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249843,160042,'Bekins','Bekins','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249844,160043,'Berkery Noyes MandASoft','Berkery Noyes MandASoft','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249845,160044,'Berkshire Hathaway','Berkshire Hathaway','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249846,160045,'BetterLesson','BetterLesson','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249847,160046,'BillGuard','BillGuard','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249848,160047,'Bing','Bing','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249849,160048,'Biovia','Biovia','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249850,160049,'BizVizz','BizVizz','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249851,160050,'BlackRock','BlackRock','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249852,160051,'Bloomberg','Bloomberg','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249853,160052,'Booz Allen Hamilton','Booz Allen Hamilton','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249854,160053,'Boston Consulting Group','Boston Consulting Group','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249855,160054,'Boundless','Boundless','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249856,160055,'Bridgewater','Bridgewater','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249857,160056,'Brightscope','Brightscope','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249858,160057,'BuildFax','BuildFax','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249859,160058,'Buildingeye','Buildingeye','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249860,160059,'BuildZoom','BuildZoom','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249861,160060,'Business and Legal Resources','Business and Legal Resources','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249862,160061,'Business Monitor International','Business Monitor International','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249863,160062,'Calcbench, Inc.','Calcbench, Inc.','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249864,160063,'Cambridge Information Group','Cambridge Information Group','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249865,160064,'Cambridge Semantics','Cambridge Semantics','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249866,160065,'CAN Capital','CAN Capital','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249867,160066,'Canon','Canon','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249868,160067,'Capital Cube','Capital Cube','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249869,160068,'Cappex','Cappex','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249870,160069,'Captricity','Captricity','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249871,160070,'CareSet Systems','CareSet Systems','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249872,160071,'Careset.com','Careset.com','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249873,160072,'CARFAX','CARFAX','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249874,160073,'Caspio','Caspio','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249875,160074,'Castle Biosciences','Castle Biosciences','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249876,160075,'CB Insights','CB Insights','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249877,160076,'Ceiba Solutions','Ceiba Solutions','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249878,160077,'Center for Responsive Politics','Center for Responsive Politics','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249879,160078,'Cerner','Cerner','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249880,160079,'Certara','Certara','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249881,160080,'CGI','CGI','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249882,160081,'Charles River Associates','Charles River Associates','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249883,160082,'Charles Schwab Corp.','Charles Schwab Corp.','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249884,160083,'Chemical Abstracts Service','Chemical Abstracts Service','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249885,160084,'Child Care Desk','Child Care Desk','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249886,160085,'Chubb','Chubb','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249887,160086,'Citigroup','Citigroup','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249888,160087,'CityScan','CityScan','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249889,160088,'CitySourced','CitySourced','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249890,160089,'Civic Impulse LLC','Civic Impulse LLC','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249891,160090,'Civic Insight','Civic Insight','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249892,160091,'Civinomics','Civinomics','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249893,160092,'Civis Analytics','Civis Analytics','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249894,160093,'Clean Power Finance','Clean Power Finance','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249895,160094,'ClearHealthCosts','ClearHealthCosts','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249896,160095,'ClearStory Data','ClearStory Data','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249897,160096,'Climate Corporation','Climate Corporation','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249898,160097,'CliniCast','CliniCast','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249899,160098,'Cloudmade','Cloudmade','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249900,160099,'Cloudspyre','Cloudspyre','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249901,160100,'Code for America','Code for America','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249902,160101,'Code-N','Code-N','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249903,160102,'Collective IP','Collective IP','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249904,160103,'College Abacus, an ECMC initiative','College Abacus, an ECMC initiative','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249905,160104,'College Board','College Board','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249906,160105,'Compared Care','Compared Care','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249907,160106,'Compendia Bioscience Life Technologies','Compendia Bioscience Life Technologies','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249908,160107,'Compliance and Risks','Compliance and Risks','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249909,160108,'Computer Packages Inc','Computer Packages Inc','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249910,160109,'CONNECT-DOT LLC.','CONNECT-DOT LLC.','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249911,160110,'ConnectEDU','ConnectEDU','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249912,160111,'Connotate','Connotate','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249913,160112,'Construction Monitor LLC','Construction Monitor LLC','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249914,160113,'Consumer Reports','Consumer Reports','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249915,160114,'CoolClimate','CoolClimate','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249916,160115,'Copyright Clearance Center','Copyright Clearance Center','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249917,160116,'CoreLogic','CoreLogic','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249918,160117,'CostQuest','CostQuest','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249919,160118,'Credit Karma','Credit Karma','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249920,160119,'Credit Sesame','Credit Sesame','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249921,160120,'CrowdANALYTIX','CrowdANALYTIX','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249922,160121,'Dabo Health','Dabo Health','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249923,160122,'DataLogix','DataLogix','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249924,160123,'DataMade','DataMade','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249925,160124,'DataMarket','DataMarket','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249926,160125,'Datamyne','Datamyne','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249927,160126,'DataWeave','DataWeave','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249928,160127,'Deloitte','Deloitte','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249929,160128,'DemystData','DemystData','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249930,160129,'Department of Better Technology','Department of Better Technology','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249931,160130,'Development Seed','Development Seed','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249932,160131,'Docket Alarm, Inc.','Docket Alarm, Inc.','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249933,160132,'Dow Jones & Co.','Dow Jones & Co.','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249934,160133,'Dun & Bradstreet','Dun & Bradstreet','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249935,160134,'Earth Networks','Earth Networks','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249936,160135,'EarthObserver App','EarthObserver App','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249937,160136,'Earthquake Alert!','Earthquake Alert!','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249938,160137,'Eat Shop Sleep','Eat Shop Sleep','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249939,160138,'Ecodesk','Ecodesk','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249940,160139,'eInstitutional','eInstitutional','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249941,160140,'Embark','Embark','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249942,160141,'EMC','EMC','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249943,160142,'Energy Points, Inc.','Energy Points, Inc.','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249944,160143,'Energy Solutions Forum','Energy Solutions Forum','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249945,160144,'Enervee Corporation','Enervee Corporation','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249946,160145,'Enigma.io','Enigma.io','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249947,160146,'Ensco','Ensco','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249948,160147,'Environmental Data Resources','Environmental Data Resources','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249949,160148,'Epsilon','Epsilon','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249950,160149,'Equal Pay for Women','Equal Pay for Women','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249951,160150,'Equifax','Equifax','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249952,160151,'Equilar','Equilar','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249953,160152,'Ernst & Young LLP','Ernst & Young LLP','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249954,160153,'eScholar LLC.','eScholar LLC.','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249955,160154,'Esri','Esri','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249956,160155,'Estately','Estately','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249957,160156,'Everyday Health','Everyday Health','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249958,160157,'Evidera','Evidera','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249959,160158,'Experian','Experian','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249960,160159,'Expert Health Data Programming, Inc.','Expert Health Data Programming, Inc.','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249961,160160,'Exversion','Exversion','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249962,160161,'Ez-XBRL','Ez-XBRL','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249963,160162,'Factset','Factset','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249964,160163,'Factual','Factual','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249965,160164,'Farmers','Farmers','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249966,160165,'FarmLogs','FarmLogs','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249967,160166,'Fastcase','Fastcase','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249968,160167,'Fidelity Investments','Fidelity Investments','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249969,160168,'FindTheBest.com','FindTheBest.com','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249970,160169,'First Fuel Software','First Fuel Software','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249971,160170,'FirstPoint, Inc.','FirstPoint, Inc.','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249972,160171,'Fitch','Fitch','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249973,160172,'FlightAware','FlightAware','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249974,160173,'FlightStats','FlightStats','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249975,160174,'FlightView','FlightView','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249976,160175,'Food+Tech Connect','Food+Tech Connect','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249977,160176,'Forrester Research','Forrester Research','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249978,160177,'Foursquare','Foursquare','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249979,160178,'Fujitsu','Fujitsu','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249980,160179,'Funding Circle','Funding Circle','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249981,160180,'FutureAdvisor','FutureAdvisor','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249982,160181,'Fuzion Apps, Inc.','Fuzion Apps, Inc.','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249983,160182,'Gallup','Gallup','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249984,160183,'Galorath Incorporated','Galorath Incorporated','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249985,160184,'Garmin','Garmin','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249986,160185,'Genability','Genability','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249987,160186,'GenoSpace','GenoSpace','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249988,160187,'Geofeedia','Geofeedia','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249989,160188,'Geolytics','Geolytics','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249990,160189,'Geoscape','Geoscape','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249991,160190,'GetRaised','GetRaised','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249992,160191,'GitHub','GitHub','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249993,160192,'Glassy Media','Glassy Media','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249994,160193,'Golden Helix','Golden Helix','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249995,160194,'GoodGuide','GoodGuide','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249996,160195,'Google Maps','Google Maps','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249997,160196,'Google Public Data Explorer','Google Public Data Explorer','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249998,160197,'Government Transaction Services','Government Transaction Services','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (249999,160198,'Govini','Govini','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250000,160199,'GovTribe','GovTribe','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250001,160200,'Govzilla, Inc.','Govzilla, Inc.','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250002,160201,'gRadiant Research LLC','James Casebere Studio','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250003,160202,'Graebel Van Lines','Domenico Casella','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250004,160203,'Graematter, Inc.','Raffaello Casellesi','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250005,160204,'Granicus','Tim Casey','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250006,160205,'GreatSchools','William Edmund Cash','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250007,160206,'GuideStar','William Vaughn Cash','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250008,160207,'H3 Biomedicine','John William Casilear','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250009,160208,'Harris Corporation','Alessandro Casolani','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250010,160209,'HDScores, Inc','Alessandro di Agostino Casolani','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250011,160210,'Headlight','Felice Antonio Casone','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250012,160211,'Healthgrades','Antonio Casoni','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250013,160212,'Healthline','Felice Casorati','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250014,160213,'HealthMap','Karl Caspar','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250015,160214,'HealthPocket, Inc.','Frank Cassara','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250016,160215,'HelloWallet','Mary Cassatt','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250017,160216,'HERE','Mary Stevenson Cassatt','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250018,160217,'Honest Buildings','Giovanni Maria Cassini','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250019,160218,'HopStop','Bruno Cassirer','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250020,160219,'Housefax','Joan Cassis','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250021,160220,'How''s My Offer?','Jean Cassou','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250022,160221,'IBM','Andrea del Castagno','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250023,160222,'ideas42','Giovanni Bernardi da Castel Bolognese','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250024,160223,'iFactor Consulting','Giovanni da Castelbolognese','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250025,160224,'IFI CLAIMS Patent Services','Robert Castell','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250026,160225,'iMedicare','Julio Castellanos','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250027,160226,'Impact Forecasting (Aon)','Bernardo Castelli','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250028,160227,'Impaq International','Bernardo Castello','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250029,160228,'Import.io','Frederico Castellon','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250030,160229,'IMS Health','Salvo Castellucci','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250031,160230,'InCadence','Giovanni Benedetto Castiglione','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250032,160231,'indoo.rs','Giuseppe Castiglione','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250033,160232,'InfoCommerce Group','Antonio del Castillo','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250034,160233,'Informatica','Liset Castillo','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250035,160234,'InnoCentive','James Castle','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250036,160235,'Innography','Alex Castro','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250037,160236,'Innovest Systems','Ray Caswell','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250038,160237,'Inovalon','Roy Caswell','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250039,160238,'Inrix Traffic','Pietro Cataneo','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250040,160239,'Intelius','Vincenzo Catenacci','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250041,160240,'Intermap Technologies','Mark Catesby','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250042,160241,'Investormill','Bernard Cathelin','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250043,160242,'Iodine','Elizabeth Catlett','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250044,160243,'IPHIX','George Catlin','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250045,160244,'iRecycle','Maria Harriet Elizabeth Cator','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250046,160245,'iTriage','Jacob Cats','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250047,160246,'IVES Group Inc','Danese Cattaneo','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250048,160247,'IW Financial','Patrick Caulfield','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250049,160248,'JJ Keller','Lillian Causey','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250050,160249,'J.P. Morgan Chase','Gilles Paul Cauvet','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250051,160250,'Junar, Inc.','Kristen Cavagnet','Company');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250052,160251,'Gianni Cacciarini','Gianni Cacciarini','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250053,160252,'Giovanni Battista Caccini','Giovanni Battista Caccini','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250054,160253,'Gerard Cachet','Gerard Cachet','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250055,160254,'Alfred Cadart','Alfred Cadart','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250056,160255,'Giuseppe Cades','Giuseppe Cades','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250057,160256,'Paul Cadmus','Paul Cadmus','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250058,160257,'Harrison Cady','Harrison Cady','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250059,160258,'Ippolito Caffi','Ippolito Caffi','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250060,160259,'John Cage','John Cage','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250061,160260,'Guido Cagnacci','Guido Cagnacci','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250062,160261,'Luigi Cagnola','Luigi Cagnola','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250063,160262,'Marcelle Cahn','Marcelle Cahn','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250064,160263,'Gustave Caillebotte','Gustave Caillebotte','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250065,160264,'Jean Caillou','Jean Caillou','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250066,160265,'Charles William Cain','Charles William Cain','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250067,160266,'Fred Cain','Fred Cain','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250068,160267,'Gasparo Cairano','Gasparo Cairano','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250069,160268,'Earl of Caithness','Earl of Caithness','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250070,160269,'il Calabrese','il Calabrese','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250071,160270,'Alexandre Calame','Alexandre Calame','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250072,160271,'Giacinto Calandrucci','Giacinto Calandrucci','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250073,160272,'Letterio Calapai','Letterio Calapai','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250074,160273,'Nicolas Calas','Nicolas Calas','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250075,160274,'Lawrence Calcagno','Lawrence Calcagno','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250076,160275,'Polidoro Caldara','Polidoro Caldara','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250077,160276,'Randolph Caldecott','Randolph Caldecott','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250078,160277,'Alexander Calder','Alexander Calder','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250079,160278,'Ludmilla Calderon','Ludmilla Calderon','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250080,160279,'Mary Steichen Calderone','Mary Steichen Calderone','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250081,160280,'James Caldwall','James Caldwall','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250082,160281,'Robert Allan Cale','Robert Allan Cale','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250083,160282,'Paolo Caliari','Paolo Caliari','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250084,160283,'Jan van Call I','Jan van Call I','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250085,160284,'Harry Callahan','Harry Callahan','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250086,160285,'Harry Morey Callahan','Harry Morey Callahan','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250087,160286,'Kenneth Callahan','Kenneth Callahan','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250088,160287,'Sophie Calle','Sophie Calle','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250089,160288,'Mark Callen','Mark Callen','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250090,160289,'Mary Callery','Mary Callery','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250091,160290,'Jo Ann Callis','Jo Ann Callis','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250092,160291,'Jacques Callot','Jacques Callot','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250093,160292,'William Callow','William Callow','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250094,160293,'Denys Calvaert','Denys Calvaert','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250095,160294,'Edward Calvert','Edward Calvert','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250096,160295,'Robert Calvin','Robert Calvin','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250097,160296,'Andrea Camassei','Andrea Camassei','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250098,160297,'Giovanni Battista Cambi','Giovanni Battista Cambi','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250099,160298,'Luca Cambiaso','Luca Cambiaso','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250100,160299,'Andrea Cambio','Andrea Cambio','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250101,160300,'Gambattista Cambio','Gambattista Cambio','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250102,160301,'Giovanni Battista Cambio','Giovanni Battista Cambio','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250103,160302,'melio','melio','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250104,160303,'Giuseppe Camerata II','Giuseppe Camerata II','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250105,160304,'Charles Cameron','Charles Cameron','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250106,160305,'David Young Cameron','David Young Cameron','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250107,160306,'Julia Margaret Cameron','Julia Margaret Cameron','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250108,160307,'Malcolm Cameron','Malcolm Cameron','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250109,160308,'Melvina Cames','Melvina Cames','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250110,160309,'Vina Jane Cochran Cames','Vina Jane Cochran Cames','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250111,160310,'Albert Camilli','Albert Camilli','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250112,160311,'mligue','mligue','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250113,160312,'Girolamo Campagna','Girolamo Campagna','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250114,160313,'Domenico Campagnola','Domenico Campagnola','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250115,160314,'Giulio Campagnola','Giulio Campagnola','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250116,160315,'Angelo Campanella','Angelo Campanella','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250117,160316,'Johann Jacob Campanus','Johann Jacob Campanus','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250118,160317,'Blendon Reed Campbell','Blendon Reed Campbell','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250119,160318,'Charles Campbell','Charles Campbell','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250120,160319,'Colen Campbell','Colen Campbell','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250121,160320,'Donald Campbell','Donald Campbell','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250122,160321,'Douglas Campbell','Douglas Campbell','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250123,160322,'Elmer Simms Campbell','Elmer Simms Campbell','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250124,160323,'Roger Campbell','Roger Campbell','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250125,160324,'Rollington Campbell','Rollington Campbell','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250126,160325,'Rose Campbell','Rose Campbell','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250127,160326,'Heinrich Campendonk','Heinrich Campendonk','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250128,160327,'Giulio Campi','Giulio Campi','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250129,160328,'Massimo Campigli','Massimo Campigli','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250130,160329,'Giovanni Domenico Campiglia','Giovanni Domenico Campiglia','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250131,160330,'Robert Campin','Robert Campin','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250132,160331,'Antonio Campo','Antonio Campo','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250133,160332,'Peter Campus','Peter Campus','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250134,160333,'Vincenzo Camuccini','Vincenzo Camuccini','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250135,160334,'Giambattista Canal','Giambattista Canal','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250136,160335,'Giovanni Antonio Canal','Giovanni Antonio Canal','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250137,160336,'naletto','naletto','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250138,160337,'Victor Candell','Victor Candell','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250139,160338,'Peter Candid','Peter Candid','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250140,160339,'Giovanni Candida','Giovanni Candida','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250141,160340,'Pietro Candido','Pietro Candido','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250142,160341,'Giacomo Caneva','Giacomo Caneva','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250143,160342,'Robert Caney','Robert Caney','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250144,160343,'Francesco Cangiullo','Francesco Cangiullo','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250145,160344,'Giovanni Angelo Canini','Giovanni Angelo Canini','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250146,160345,'Joseph Cannella','Joseph Cannella','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250147,160346,'Rafael Canogar','Rafael Canogar','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250148,160347,'Antonio Canova','Antonio Canova','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250149,160348,'Remigio Cantagallina','Remigio Cantagallina','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250150,160349,'Maria Boveri Cantarella','Maria Boveri Cantarella','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250151,160350,'Simone Cantarini','Simone Cantarini','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250152,160351,'Domenico Maria Canuti','Domenico Maria Canuti','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250153,160352,'Michele Canzio','Michele Canzio','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250154,160353,'Ernest Capaldo','Ernest Capaldo','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250155,160354,'Rhys Caparn','Rhys Caparn','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250156,160355,'Antonio Capellan','Antonio Capellan','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250157,160356,'Giacinto Capelli','Giacinto Capelli','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250158,160357,'Bernardino Capitelli','Bernardino Capitelli','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250159,160358,'Giuseppe Capogrossi','Giuseppe Capogrossi','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250160,160359,'Angelica Caporaso','Angelica Caporaso','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250161,160360,'Jan van de Cappelle','Jan van de Cappelle','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250162,160361,'Leonetto Cappiello','Leonetto Cappiello','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250163,160362,'pponi','pponi','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250164,160363,'Charles Merrick Capps','Charles Merrick Capps','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250165,160364,'il Cappuccio','il Cappuccio','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250166,160365,'Alessandro Capra','Alessandro Capra','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250167,160366,'Elmer Capshaw','Elmer Capshaw','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250168,160367,'Lily Capson','Lily Capson','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250169,160368,'Jose Manuel Capuletti','Jose Manuel Capuletti','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250170,160369,'Jean Gabriel Caquet','Jean Gabriel Caquet','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250171,160370,'Kathleen Caraccio','Kathleen Caraccio','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250172,160371,'Roberto Caracciolo','Roberto Caracciolo','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250173,160372,'radosso','radosso','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250174,160373,'Gian Jacopo Caraglio','Gian Jacopo Caraglio','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250175,160374,'Giovanni Jacopo Caraglio','Giovanni Jacopo Caraglio','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250176,160375,'Vincent Carano','Vincent Carano','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250177,160376,'Girolamo Carattoni','Girolamo Carattoni','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250178,160377,'ravaggio','ravaggio','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250179,160378,'Michelangelo Merisi da Caravaggio','Michelangelo Merisi da Caravaggio','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250180,160379,'Polidoro da Caravaggio','Polidoro da Caravaggio','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250181,160380,'Ludovico Carazzari','Ludovico Carazzari','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250182,160381,'Antonio Carbonati','Antonio Carbonati','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250183,160382,'Marin Carburi de Ceffalonie','Marin Carburi de Ceffalonie','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250184,160383,'Agustin Cardenas','Agustin Cardenas','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250185,160384,'Lodovico Cardi','Lodovico Cardi','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250186,160385,'Charles Cardinale','Charles Cardinale','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250187,160386,'Sauro Cardinale','Sauro Cardinale','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250188,160387,'Marco Cardisco','Marco Cardisco','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250189,160388,'Anthony Cardon','Anthony Cardon','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250190,160389,'Vicenzio Carducci','Vicenzio Carducci','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250191,160390,'Vicencio Carducho','Vicencio Carducho','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250192,160391,'Vicente Carducho','Vicente Carducho','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250193,160392,'riani','riani','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250194,160393,'Giovanni Cariani','Giovanni Cariani','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250195,160394,'Catherine Carine','Catherine Carine','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250196,160395,'Mathias Carl','Mathias Carl','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250197,160396,'Arthur Beecher Carles','Arthur Beecher Carles','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250198,160397,'Luca Carlevariis','Luca Carlevariis','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250199,160398,'Luca Carlevarijs','Luca Carlevarijs','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250200,160399,'Don Carli','Don Carli','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250201,160400,'Marie Carlier','Marie Carlier','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250202,160401,'Martin Carlin','Martin Carlin','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250203,160402,'Steve Carlisle','Steve Carlisle','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250204,160403,'rlo Veneziano','rlo Veneziano','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250205,160404,'Carlo Innocenzo Carlone','Carlo Innocenzo Carlone','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250206,160405,'Emil Carlsen','Emil Carlsen','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250207,160406,'Soren Emil Carlsen','Soren Emil Carlsen','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250208,160407,'Albert Carman','Albert Carman','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250209,160408,'rmontelle','rmontelle','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250210,160409,'Fra Carnevale','Fra Carnevale','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250211,160410,'Anthony Caro','Anthony Caro','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250212,160411,'Adolphe Alexandre Joseph Caron','Adolphe Alexandre Joseph Caron','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250213,160412,'Antoine Caron','Antoine Caron','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250214,160413,'Paolo Carosone','Paolo Carosone','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250215,160414,'Vittore Carpaccio','Vittore Carpaccio','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250216,160415,'Francis Bicknell Carpenter','Francis Bicknell Carpenter','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250217,160416,'Ugo da Carpi','Ugo da Carpi','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250218,160417,'Giulio Carpioni','Giulio Carpioni','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250219,160418,'Jack Carr','Jack Carr','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250220,160419,'John Carr','John Carr','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250221,160420,'John Carr of York','John Carr of York','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250222,160421,'Agostino Carracci','Agostino Carracci','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250223,160422,'Annibale Carracci','Annibale Carracci','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250224,160423,'Francesco Carracci','Francesco Carracci','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250225,160424,'Lodovico Carracci','Lodovico Carracci','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250226,160425,'Antoine Carree','Antoine Carree','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250227,160426,'Rosalba Carriera','Rosalba Carriera','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250228,160427,'Leonora Carrington','Leonora Carrington','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250229,160428,'called Carmontelle Carrogis','called Carmontelle Carrogis','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250230,160429,'John Carroll','John Carroll','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250231,160430,'Lewis Carroll','Lewis Carroll','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250232,160431,'Laurent Cars','Laurent Cars','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250233,160432,'Jon Carsman','Jon Carsman','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250234,160433,'Karen Carson','Karen Carson','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250235,160434,'Vincenzo Cartari','Vincenzo Cartari','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250236,160435,'Clarence Holbrook Carter','Clarence Holbrook Carter','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250237,160436,'Erskine Carter','Erskine Carter','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250238,160437,'John Carter','John Carter','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250239,160438,'William Carter','William Carter','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250240,160439,'Ferdinand Cartier','Ferdinand Cartier','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250241,160440,'Norman Carton','Norman Carton','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250242,160441,'Jacopo Carucci','Jacopo Carucci','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250243,160442,'Carl Gustav Carus','Carl Gustav Carus','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250244,160443,'A Cary','A Cary','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250245,160444,'William De La Montagne Cary','William De La Montagne Cary','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250246,160445,'Francesco Casanova','Francesco Casanova','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250247,160446,'Edmond Casarella','Edmond Casarella','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250248,160447,'Michael Cascadden','Michael Cascadden','Individual');
INSERT INTO Applicants(Application_ID,Applicant_ID,Name,Inventor,Applicant_Status) VALUES (250249,160448,'Charles Caseau','Charles Caseau','Individual');
