CREATE TABLE Partners(
   Partner_ID INTEGER  NOT NULL PRIMARY KEY 
  ,Name       VARCHAR(37) NOT NULL
  ,Status     VARCHAR(10) NOT NULL
);
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370000,'Henry Corbould','Individual');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370001,'Lucille Corcos','Individual');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370002,'Jean Louis de Cordemoy','Individual');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370003,'Christopher Cordes','Individual');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370004,'Robert Cordier','Individual');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370005,'Lovis Corinth','Individual');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370006,'Bartolomeo Coriolano','Individual');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370007,'rmano','Individual');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370008,'rneille','Individual');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370009,'Claude Corneille','Individual');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370010,'Cornelis van Beverloo Corneille','Individual');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370011,'Michel Corneille','Individual');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370012,'Michel Ange Corneille','Individual');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370013,'rneille de la Haye','Individual');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370014,'rneille de Lyon','Individual');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370015,'Cornelis Cornelisz van Haarlem','Individual');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370016,'Jacob Cornelisz van Oostsanen','Individual');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370017,'Peter von Cornelius','Individual');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370018,'Joseph Cornell','Individual');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370019,'Thomas Browne Cornell','Individual');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370020,'Susan Cornish','Individual');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370021,'Bartolomeo di Giovanni Corradini','Individual');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370022,'Lodovico Corradini','Individual');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370023,'rreggio','Individual');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370024,'Richard Correll','Individual');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370025,'Gilles Corrozet','Individual');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370026,'Mary Ann Corse','Individual');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370027,'Marcantonio Corsi','Individual');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370028,'Cliff Corson','Individual');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370029,'Cornelis Cort','Individual');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370030,'Hendrik Frans de Cort','Individual');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370031,'Josse de Cort','Individual');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370032,'Guglielmo Cortese','Individual');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370033,'Pietro Berrettini da Cortona','Individual');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370034,'Eldzier Cortor','Individual');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370035,'Charles Abel Corwin','Individual');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370036,'sci','Individual');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370037,'Alice Cosgrove','Individual');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370038,'Francesco del Cossa','Individual');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370039,'Jan Cossiers','Individual');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370040,'Giovanni Francesco Costa','Individual');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370041,'Lorenzo Costa','Individual');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370042,'Olga Costa','Individual');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370043,'Giovanni Battista Costaguti','Individual');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370044,'stanzo da Ferrara','Individual');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370045,'David Coster','Individual');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370046,'Germaine Marguerite de Coster','Individual');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370047,'Lorenzo Costa','Individual');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370048,'Olga Costa','Individual');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370049,'Giovanni Battista Costaguti','Individual');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370050,'stanzo da Ferrara','Individual');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370051,'David Coster','Individual');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370052,'Germaine Marguerite de Coster','Individual');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370053,'John Edward Costigan','Individual');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370054,'Maria Cosway','Individual');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370055,'Maria Louisa Catherine Cecilia Cosway','Individual');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370056,'Richard Cosway','Individual');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370057,'Francis Cotes','Individual');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370058,'John Sell Cotman','Individual');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370059,'Pierre Cottart','Individual');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370060,'Charles Cottet','Individual');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370061,'Robert Cottingham','Individual');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370062,'Marsha Cottrell','Individual');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370063,'Mildred Marion Coughlin','Individual');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370064,'Emile Coulon','Individual');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370065,'Jean de Courbes','Individual');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370066,'Gustave Courbet','Individual');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370067,'Jean de Court','Individual');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370068,'Georges Courteline','Individual');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370069,'Martial Courteys','Individual');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370070,'Pierre Courtin','Individual');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370071,'Jean Courtonne','Individual');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370072,'Charles Courtry','Individual');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370073,'Jean the Elder Cousin','Individual');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370074,'Jean the Younger Cousin','Individual');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370075,'Jean Cousin the Elder','Individual');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370076,'Jean Cousin the Younger','Individual');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370077,'Samuel Cousins','Individual');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370078,'Guillaume Martin Couture','Individual');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370079,'Thomas Couture','Individual');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370080,'Edouard Couturier','Individual');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370081,'Stephane Couturier','Individual');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370082,'Jean Couvay','Individual');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370083,'Philip van Couwenbergh','Individual');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370084,'Miguel Covarrubias','Individual');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370085,'Harrison Covington','Individual');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370086,'Harrison Wall Covington','Individual');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370087,'Maude Alice Cowles','Individual');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370088,'David Cox','Individual');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370089,'Douglas Cox','Individual');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370090,'Gardner Cox','Individual');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370091,'John Rogers Cox','Individual');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370092,'Kenyon Cox','Individual');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370093,'Palmer Cox','Individual');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370094,'Sharon Cox','Individual');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370095,'Reginald Cleveland Coxe','Individual');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370096,'John Coy','Individual');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370097,'Joseph Coyle','Individual');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370098,'Petah Coyne','Individual');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370099,'Antoine Coypel','Individual');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370100,'Social Health Insights','Company');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370101,'SocialEffort Inc','Company');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370102,'Socrata','Company');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370103,'Solar Census','Company');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370104,'SolarList','Company');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370105,'Sophic Systems Alliance','Company');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370106,'S&P Capital IQ','Company');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370107,'SpaceCurve','Company');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370108,'SpeSo Health','Company');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370109,'Spikes Cavell Analytic Inc','Company');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370110,'Splunk','Company');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370111,'Spokeo','Company');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370112,'SpotCrime','Company');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370113,'SpotHero.com','Company');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370114,'Stamen Design','Company');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370115,'Standard and Poor''s','Company');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370116,'State Farm Insurance','Company');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370117,'Sterling Infosystems','Company');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370118,'Stevens Worldwide Van Lines','Company');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370119,'STILLWATER SUPERCOMPUTING INC','Company');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370120,'StockSmart','Company');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370121,'Stormpulse','Company');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370122,'StreamLink Software','Company');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370123,'StreetCred Software, Inc','Company');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370124,'StreetEasy','Company');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370125,'Suddath','Company');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370126,'Symcat','Company');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370127,'Synthicity','Company');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370128,'T. Rowe Price','Company');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370129,'Tableau Software','Company');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370130,'TagniFi','Company');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370131,'Telenav','Company');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370132,'Tendril','Company');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370133,'Teradata','Company');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370134,'The Advisory Board Company','Company');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370135,'The Bridgespan Group','Company');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370136,'The DocGraph Journal','Company');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370137,'The Govtech Fund','Company');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370138,'The Schork Report','Company');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370139,'The Vanguard Group','Company');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370140,'Think Computer Corporation','Company');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370141,'Thinknum','Company');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370142,'Thomson Reuters','Company');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370143,'TopCoder','Company');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370144,'TowerData','Company');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370145,'TransparaGov','Company');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370146,'TransUnion','Company');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370147,'TrialTrove','Company');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370148,'TrialX','Company');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370149,'Trintech','Company');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370150,'TrueCar','Company');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370151,'Trulia','Company');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370152,'TrustedID','Company');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370153,'TuvaLabs','Company');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370154,'Uber','Company');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370155,'Unigo LLC','Company');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370156,'United Mayflower','Company');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370157,'Urban Airship','Company');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370158,'Urban Mapping, Inc','Company');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370159,'US Green Data','Company');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370160,'U.S. News Schools','Company');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370161,'USAA Group','Company');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370162,'USSearch','Company');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370163,'Verdafero','Company');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370164,'Vimo','Company');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370165,'VisualDoD, LLC','Company');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370166,'Vital Axiom | Niinja','Company');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370167,'VitalChek','Company');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370168,'Vitals','Company');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370169,'Vizzuality','Company');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370170,'Votizen','Company');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370171,'Walk Score','Company');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370172,'WaterSmart Software','Company');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370173,'WattzOn','Company');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370174,'Way Better Patents','Company');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370175,'Weather Channel','Company');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370176,'Weather Decision Technologies','Company');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370177,'Weather Underground','Company');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370178,'WebFilings','Company');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370179,'Webitects','Company');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370180,'WebMD','Company');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370181,'Weight Watchers','Company');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370182,'WeMakeItSafer','Company');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370183,'Wheaton World Wide Moving','Company');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370184,'Whitby Group','Company');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370185,'Wolfram Research','Company');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370186,'Wolters Kluwer','Company');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370187,'Workhands','Company');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370188,'Xatori','Company');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370189,'Xcential','Company');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370190,'xDayta','Company');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370191,'Xignite','Company');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370192,'Yahoo','Company');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370193,'Zebu Compliance Solutions','Company');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370194,'Yelp','Company');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370195,'YourMapper','Company');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370196,'Zillow','Company');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370197,'ZocDoc','Company');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370198,'Zonability','Company');
INSERT INTO Partners(Partner_ID,Name,Status) VALUES (370199,'Zoner','Company');
