CREATE TABLE Patent_Attorneys(
   Patent_Attorney_ID INTEGER  NOT NULL PRIMARY KEY 
  ,Name               VARCHAR(31) NOT NULL
  ,Office_ID          INTEGER  NOT NULL
  ,Salary             INTEGER  NOT NULL
  ,Firm               VARCHAR(49) NOT NULL
  ,Experience         INTEGER  NOT NULL
);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345001,'William Perkins Babcock',1,162500,'Kirkland & Ellis',0);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345002,'Dirck van Baburen',2,162500,'Latham & Watkins',0);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345003,'Ferdinand Bac',3,162500,'Baker McKenzie  verein',0);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345004,'cchiacca',4,162500,'DLA Piper  verein',0);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345005,'Ferdinand Sigismond Bach',1,162500,'Skadden',0);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345006,'Julie Bach',2,182500,'Dentons  verein',0);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345007,'Herman Ilfeld Bacharach',3,182500,'Clifford Chance',0);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345008,'Gaston Bachelard',4,182500,'Sidley Austin',0);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345009,'Otto Henry Bacher',1,182500,'Hogan Lovells  verein',1);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345010,'chiacca',2,182500,'Allen & Overy',1);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345011,'ciccia',3,202500,'Morgan   Lewis & Bockius',1);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345012,'ciccio',4,202500,'Linklaters',1);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345013,'Ludolf Backhuysen',1,202500,'Jones Day',1);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345014,'Francis Bacon',2,202500,'Norton Rose Fulbright  verein',1);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345015,'Peggy Bacon',3,202500,'Freshfields Bruckhaus Deringer',1);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345016,'Sisto Badalocchio',4,222500,'White & Case',1);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345017,'Aiko Baden',1,222500,'Gibson   Dunn & Crutcher',2);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345018,'Ken Baden',2,222500,'Ropes & Gray',2);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345019,'Stanley Baden',3,222500,'Greenberg Traurig',2);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345020,'Herman Bader',4,222500,'CMS  EEIG',2);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345021,'Joseph Badger',1,242500,'Sullivan & Cromwell',2);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345022,'Libero Badii',2,242500,'Weil   Gotshal & Manges',2);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345023,'Ferdinand Badin',3,242500,'Simpson Thacher & Bartlett',2);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345024,'George Baer',4,242500,'Mayer Brown',2);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345025,'Jo Baer',1,242500,'Paul   Weiss   Rifkind   Wharton & Garrison',3);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345026,'Martin Baes',2,262500,'Davis Polk & Wardwell',3);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345027,'Ernst Willem Jan Bagelaar',3,262500,'Quinn Emanuel Urquhart & Sullivan',3);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345028,'Lloyd Baggs',4,262500,'Cleary Gottlieb Steen & Hamilton',3);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345029,'Giovanni Baglione',1,262500,'Herbert Smith Freehills',3);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345030,'Cesare da Bagno',2,262500,'King & Spalding',3);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345031,'Evelyn Bailey',3,282500,'Wilmer Cutler Pickering Hale and Dorr',3);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345032,'Oscar Bailey',4,282500,'Reed Smith',3);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345033,'William Bailey',1,282500,'Paul Hastings',4);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345034,'Captain Baillie',2,282500,'Cooley',4);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345035,'William Baillie',3,282500,'King & Wood Mallesons  verein',4);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345036,'Pieter de Bailliu',4,302500,'Morrison & Foerster',4);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345037,'Pieter de the Elder Bailliu',1,302500,'Akin Gump Strauss Hauer & Feld',4);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345038,'Enrico Baj',2,302500,'Goodwin Procter',4);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345039,'Lamar Baker',3,302500,'Eversheds Sutherland',4);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345040,'Lynn Baker',4,302500,'Squire Patton Boggs  verein',4);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345041,'Oliver Mozart Baker',1,322500,'K&L Gates',5);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345042,'Tim Baker',2,322500,'Winston & Strawn',5);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345043,'Timothy Baker',3,322500,'Dechert',5);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345044,'William Robert Baker',4,322500,'Orrick   Herrington & Sutcliffe',5);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345045,'Ludolf Bakhuysen',1,322500,'Arnold & Porter',5);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345046,'Leon Bakst',2,342500,'Covington & Burling',5);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345047,'Leon Nicolaevitch Bakst',3,342500,'McDermott   Will & Emery',5);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345048,'Lev Samoilovich Bakst',4,342500,'Shearman & Sterling',5);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345049,'Dirk Baksteen',1,342500,'Milbank   Tweed   Hadley & McCloy',6);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345050,'Mark Balakjian',2,342500,'Proskauer Rose',6);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345051,'lco',3,362500,'Kim & Chang',6);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345052,'Lowell Leroy Balcom',4,362500,'Holland & Knight',6);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345053,'ldassare da Siena',1,362500,'Debevoise & Plimpton',6);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345054,'ldassare da Volterra',2,362500,'Wilson   Sonsini   Goodrich & Rosati',6);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345055,'ldassare Estense',3,362500,'Perkins Coie',6);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345056,'John Baldassari',4,382500,'Alston & Bird',6);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345057,'Lucas Baldes',1,382500,'Willkie Farr & Gallagher',7);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345058,'John Baldessari',2,382500,'Wachtell   Lipton   Rosen & Katz',7);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345059,'John Anthony Baldessari',3,382500,'O Melveny & Myers',7);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345060,'Bernardino Baldi',4,382500,'Slaughter and May',7);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345061,'Baccio Baldini',1,402500,'Baker Botts',7);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345062,'Bartolomeo Baldini',2,402500,'Vinson & Elkins',7);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345063,'Cyrus LeRoy Baldridge',3,402500,'Ashurst',7);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345064,'Giovanni Balducci',4,402500,'McGuireWoods',7);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345065,'Giovanni Balducci',1,402500,'Clyde & Co',8);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345066,'Hans Baldung',2,422500,'Cravath   Swaine & Moore',8);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345067,'Hans Baldung Grien',3,422500,'Foley & Lardner',8);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345068,'John Baldwin',4,422500,'Sheppard   Mullin   Richter & Hampton',8);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345069,'Robert Baldwin',1,422500,'Baker & Hostetler',8);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345070,'Antonio Balestra',2,422500,'Seyfarth Shaw',8);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345071,'Helen Balfour',3,442500,'Fried   Frank   Harris   Shriver & Jacobson',8);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345072,'Maxwell Balfour',4,442500,'Bryan Cave',8);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345073,'Kathryn Uhl Ball',1,442500,'Pillsbury Winthrop Shaw Pittman',9);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345074,'Lillian Ball',2,442500,'Gowling WLG',9);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345075,'Giacomo Balla',3,442500,'Pinsent Masons',9);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345076,'Chris Ballantyne',4,462500,'Fragomen   Del Rey   Bernsen & Loewy',9);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345077,'Harold Ballerd',1,462500,'Katten Muchin Rosenman',9);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345078,'Albert de Balleroy',2,462500,'Osler   Hoskin & Harcourt',9);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345079,'Maxil Ballinger',3,462500,'Hunton & Williams',9);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345080,'Leah Balsham',4,462500,'Allens',9);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345081,'Louis Pierre Baltard',1,482500,'Venable LLP',10);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345082,'Pieter Balten',2,482500,'Littler Mendelson',10);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345083,'Pieter Baltens',3,482500,'Troutman Sanders',10);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345084,'Carel Balth',4,482500,'Locke Lord',10);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345085,'lthasar Klossowski de Rola',1,482500,'Faegre Baker Daniels',10);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345086,'lthus',2,502500,'Blake   Cassels & Graydon',10);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345087,'ltimore Lord',3,502500,'Polsinelli',10);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345088,'Lewis Baltz',4,502500,'Nixon Peabody',10);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345089,'Luigi Balugani',1,502500,'Lewis Brisbois Bisgaard & Smith',11);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345090,'il Bambaia',2,502500,'Ogletree   Deakins   Nash   Smoak & Stewart',11);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345091,'mboccio',3,522500,'Duane Morris',11);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345092,'William Bambridge',4,522500,'Drinker Biddle & Reath',11);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345093,'Pieter van der Banck',1,522500,'McCarthy Tetrault',11);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345094,'Baccio Bandinelli',2,522500,'Simmons & Simmons',11);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345095,'Bartolomeo Bandinelli',3,522500,'Fox Rothschild',11);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345096,'Moses Bank',4,542500,'Jenner & Block',11);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345097,'Thomas Banks',1,542500,'Yingke',12);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345098,'Walter Darby Bannard',2,542500,'Zhong Lun',12);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345099,'Alexander Bannerman',3,542500,'Bird & Bird',12);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345100,'Beatrice Harper Banning',4,542500,'Blank Rome',12);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345101,'Belle Baranceaneau',1,562500,'Williams & Connolly',12);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345102,'Belle Goldschlager Baranceaneau',2,562500,'Schulte Roth & Zabel',12);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345103,'Antonio Baratta',3,562500,'Kilpatrick Townsend & Stockton',12);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345104,'Daniel Barbaro',4,562500,'Jackson Lewis',12);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345105,'Bernardino Barbatelli',1,562500,'Crowell & Moring',13);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345106,'Jean Barbault',2,582500,'Fish & Richardson',13);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345107,'Francesco Barbazza',3,582500,'Cozen O Connor',13);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345108,'Jack Barber',4,582500,'Boies   Schiller   Flexner',13);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345109,'Jean Barbet',1,582500,'Cadwalader   Wickersham & Taft',13);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345110,'Antonio Barbey',2,582500,'Nelson Mullins Riley & Scarborough',13);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345111,'Domenico del Barbiere',3,602500,'Garrigues',13);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345112,'Giovanni Francesco Barbieri',4,602500,'Mintz   Levin   Cohn   Ferris   Glovsky & Popeo',13);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345113,'Salvador Barbudo Sanchez',1,602500,'Haynes and Boone',14);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345114,'James Bard',2,602500,'Barnes & Thornburg',14);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345115,'Phillip Bard',3,602500,'Baker   Donelson   Bearman   Caldwell & Berkowitz',14);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345116,'Jean Hippolyte Bardin',4,622500,'Taylor Wessing',14);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345117,'Guy Bardone',1,622500,'AllBright Law Offices',14);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345118,'rend van Brussel',2,622500,'Cahill Gordon & Reindel',14);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345119,'Dirck Barendsz',3,622500,'Kramer Levin Naftalis & Frankel',14);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345120,'Jared Bark',4,622500,'Fidal',14);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345121,'Albert Winslow Barker',1,642500,'Akerman LLP',15);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345122,'George Barker',2,642500,'Clayton Utz',15);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345123,'John Jesse Barker',3,642500,'Fenwick & West',15);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345124,'Thomas Barker',4,642500,'Berwin Leighton Paisner',15);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345125,'rker of Bath',1,642500,'Steptoe & Johnson',15);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345126,'Ernst Barlach',2,662500,'Fasken',15);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345127,'Francis Barlow',3,662500,'Davis Wright Tremaine',15);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345128,'Inigo Barlow',4,662500,'Ballard Spahr',15);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345129,'Lou Barlow',1,662500,'Loyens & Loeff',16);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345130,'Louis Barlow',2,662500,'Shook   Hardy & Bacon',16);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345131,'Herbert Barnard',3,682500,'Husch Blackwell',16);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345132,'rnes',4,682500,'Borden Ladner Gervais',16);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345133,'Ada Barnes',1,682500,'Pepper Hamilton',16);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345134,'Will Barnet',2,682500,'MinterEllison',16);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345135,'Gerard Barnett',3,682500,'Dorsey & Whitney',16);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345136,'Herbert Phillip Barnett',4,702500,'Gordon Rees Scully Mansukhani',16);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345137,'Richard Barnett',1,702500,'Hughes Hubbard & Reed',17);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345138,'Tina Barney',2,702500,'Manatt   Phelps & Phillips',17);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345139,'Melanie Eve Barocas',3,702500,'Wilson Elser Moskowitz Edelman & Dicker',17);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345140,'Federico Barocci',4,702500,'Addleshaw Goddard',17);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345141,'Jill Baroff',1,722500,'Irwin Mitchell',17);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345142,'Acavie Baron',2,722500,'Finnegan   Henderson   Farabow   Garrett & Dunner',17);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345143,'Bernard Baron',3,722500,'Osborne Clarke',17);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345144,'Hannelore Baron',4,722500,'Loeb & Loeb',17);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345145,'Henri Charles Antoine Baron',1,722500,'DWF',18);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345146,'Giuseppe Baroni',2,742500,'Arent Fox',18);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345147,'Martin Barooshian',3,742500,'Stikeman Elliott',18);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345148,'Burt Barr',4,742500,'DAC Beachcroft',18);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345149,'Norman Barr',1,742500,'DeHeng Law Offices',18);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345150,'Johan Barra',2,742500,'Grandall Law Firm',18);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345151,'Eugene Barrell',3,762500,'Bradley Arant Boult Cummings',18);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345152,'Carlo Barrera',4,762500,'Womble Carlyle Sandridge & Rice',18);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345153,'George Barret',1,762500,'Buchanan   Ingersoll & Rooney',19);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345154,'Lawrence Barrett',2,762500,'Andrews Kurth Kenyon',19);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345155,'Thomas Weeks Barrett',3,762500,'Cuatrecasas   Gon alves Pereira',19);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345156,'Conrado Barrio',4,782500,'Bracewell LLP',19);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345157,'Thomas Barrow',1,782500,'Hengeler Mueller',19);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345158,'Charles Barrows',2,782500,'Lowenstein Sandler',19);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345159,'Anna Barry',3,782500,'Quarles & Brady',19);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345160,'James Barry',4,782500,'Fieldfisher',19);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345161,'Robert Barry',1,802500,'Snell & Wilmer',20);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345162,'Andrzej Bartczak',2,802500,'Macfarlanes',20);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345163,'Marcia Bartholme',3,802500,'Kennedys Law',20);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345164,'Edward Sheffield Bartholomew',4,802500,'Vedder Price',20);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345165,'Dana Bartlett',1,802500,'Stroock & Stroock & Lavan',20);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345166,'Elwood Warren Bartlett',2,822500,'Jackson Walker',20);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345167,'Ivan Bartlett',3,822500,'Holland & Hart',20);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345168,'Jennifer Bartlett',4,822500,'Rodl & Partner',20);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345169,'Jennifer Losch Bartlett',1,822500,'Stinson Leonard Street',21);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345170,'Richard Franklin Bartlett',2,822500,'Bae Kim & Lee',21);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345171,'William Henry Bartlett',3,842500,'Stephenson Harwood',21);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345172,'Francesco Bartoli',4,842500,'Dinsmore & Shohl',21);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345173,'Pietro Santo Bartoli',1,842500,'Kelley Drye & Warren',21);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345174,'Lorenzo Bartolini',2,842500,'McCarter & English',21);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345175,'Luciano Bartolini',3,842500,'Munger   Tolles & Olson',21);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345176,'Andrea di Bartolo',4,862500,'Choate   Hall & Stewart',21);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345177,'Domenico di Bartolo da Venezia',1,862500,'Kutak Rock',22);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345178,'Andrea di Bartolo di Simone',2,862500,'HFW  previously Holman Fenwick Willan',22);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345179,'rtolomeo da Murano',3,862500,'Withers LLP',22);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345180,'rtolomeo Veneto',4,862500,'Frost Brown Todd',22);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345181,'Fra Bartolommeo',1,882500,'Wiley Rein',22);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345182,'rtolommeo di Paolo',2,882500,'Dickinson Wright',22);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345183,'Francesco Bartolozzi',3,882500,'Knobbe   Martens   Olson & Bear',22);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345184,'Cleon Barton',4,882500,'Saul Ewing Arnstein & Lehr',22);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345185,'Loren Roberta Barton',1,882500,'Jun He Law Offices',23);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345186,'Robert Barton',2,902500,'Hinshaw & Culbertson LLP',23);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345187,'Adam von Bartsch',3,902500,'Winstead PC',23);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345188,'Walter Frederick Bartsch',4,902500,'Kasowitz Benson Torres',23);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345189,'Eugene Bartz',1,902500,'Gide Loyrette Nouel',23);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345190,'Hendrick Bary',2,902500,'Dykema Gossett',23);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345191,'Marco Basaiti',3,922500,'Thompson & Knight',23);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345192,'Afro Basaldella',4,922500,'Honigman Miller Schwartz and Cohn',23);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345193,'san',1,922500,'Stoel Rives',24);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345194,'Ruth Henshaw Bascom',2,922500,'Marshall   Dennehey   Warner   Coleman & Goggin',24);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345195,'Johann Bernhard Basedow',3,922500,'Watson Farley & Williams',24);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345196,'Georg Baselitz',4,942500,'Mishcon de Reya',24);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345197,'Edward Bashaw',1,942500,'Thompson Hine',24);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345198,'James Basire I',2,942500,'Chapman and Cutler',24);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345199,'Leonard Baskin',3,942500,'Schiff Hardin',24);
INSERT INTO Patent_Attorneys(Patent_Attorney_ID,Name,Office_ID,Salary,Firm,Experience) VALUES (345200,'Antonio Basoli',4,942500,'Corrs Chambers Westgarth',24);
