CREATE TABLE Patentees(
   Patentee_ID       INTEGER  NOT NULL PRIMARY KEY 
  ,Patentee_Name     VARCHAR(59) NOT NULL
  ,Patentee_Category VARCHAR(11) NOT NULL
);
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100000,'Jocelyn T. Marsh','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100005,'Patricia Z. Patton','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100010,'Chandler L. Hester','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100015,'Ann N. Wade','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100024,'George F. Arnold','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100026,'Hermione M. Moore','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100034,'Mara F. Larson','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100042,'Fuller D. Morton','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100043,'Timothy N. Contreras','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100051,'Katell N. Weaver','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100053,'Signe A. Velasquez','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100055,'Berk N. Garrett','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100062,'Hayden F. Roy','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100071,'Edan T. Quinn','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100075,'Quemby P. Nielsen','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100080,'Miriam R. Romero','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100081,'George U. Fisher','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100087,'Raja L. Garner','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100090,'Bethany B. Craft','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100096,'Aidan Z. Callahan','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100101,'Zenaida Z. Holden','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100102,'Bertha H. Hoover','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100105,'Colin N. Ryan','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100110,'Garrison Y. Sharpe','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100119,'Ria Y. Franks','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100128,'Uriel V. Wilcox','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100131,'Ross O. Callahan','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100140,'Fletcher O. Howard','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100145,'Owen I. Cruz','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100146,'Olga D. Kim','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100150,'Nicholas M. Hall','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100156,'Taylor Z. Terry','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100160,'Libby H. Fulton','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100164,'Jameson A. Flores','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100167,'Kyra H. Gonzalez','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100173,'Piper G. Casey','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100181,'Fitzgerald M. Guerrero','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100184,'Taylor J. Hancock','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100190,'Simone X. Lewis','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100191,'Carolyn G. Ware','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100196,'Simone D. Pena','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100198,'Christian J. Burks','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100203,'Blair Q. Sherman','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100211,'Joshua Z. Frazier','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100219,'Keegan Y. Bray','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100225,'Calista K. Ratliff','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100234,'Gwendolyn C. Hood','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100238,'Lester T. Johnson','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100239,'Dillon P. Alvarado','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100240,'Ariana E. Kent','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100247,'Simon I. Castro','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100250,'Reuben A. Knowles','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100252,'Isabelle G. Hahn','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100258,'Jarrod W. Wall','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100265,'Lois I. Cole','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100268,'Bernard W. Gallegos','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100269,'Suki F. Yang','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100277,'Ella F. Hampton','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100286,'Joy U. Blake','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100290,'Timothy H. Alford','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100295,'Mark J. Raymond','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100298,'Alec H. Porter','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100305,'Whilemina M. Vance','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100308,'Steven J. Oneil','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100317,'Patrick U. Carter','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100322,'Tatiana M. Noel','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100330,'Mufutau M. Rollins','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100336,'Camille L. Tate','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100338,'Kuame S. Marsh','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100344,'Brielle F. Marquez','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100346,'Jasmine P. Abbott','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100355,'Gloria M. Moss','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100364,'Gregory U. Levine','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100368,'Grant S. Wilcox','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100370,'Malachi D. Velez','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100371,'Jonas N. Baker','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100380,'Lillian L. Burt','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100386,'Lois F. Cantrell','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100395,'Lisandra V. Lopez','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100401,'Hayes K. Holder','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100405,'Molly A. Brennan','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100410,'Willa Q. Nunez','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100415,'Anthony O. Sweeney','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100420,'Preston S. Sims','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100427,'Solomon I. Mathis','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100432,'Martena Q. Powell','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100434,'Elton P. Sheppard','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100438,'Samuel Z. Hicks','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100440,'Claudia S. England','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100442,'Neve E. Sheppard','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100443,'Wynter J. Farley','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100444,'Dorian H. Foreman','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100446,'Cedric A. Logan','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100455,'Michelle R. Hyde','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100458,'Uriel G. Lester','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100467,'Dexter P. Stark','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100469,'Drake F. Morrison','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100472,'Vivien N. Patterson','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100475,'Grace A. Workman','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100484,'Preston D. Gallegos','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100492,'Clinton N. Nash','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100501,'Aretha Q. Snider','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100508,'Connor Y. Alvarado','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100511,'Yvette N. Walsh','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100516,'Ezra G. Preston','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100524,'Kathleen L. Steele','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100525,'Kaye J. Delaney','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100526,'Tanya U. Mcmahon','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100531,'Cynthia A. Hensley','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100535,'Howard I. Yang','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100539,'Nehru D. Mcclain','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100548,'Brett E. Wilder','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100551,'Kelsie R. Harding','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100554,'Signe F. Mills','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100562,'Victor Z. Martin','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100564,'Zachary W. Long','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100568,'Tobias H. Sparks','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100569,'Barclay K. Oneal','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100578,'Wylie A. Holmes','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100582,'Nathaniel Q. Kinney','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100587,'Jana W. Singleton','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100593,'Marshall I. Huber','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100598,'Adena L. Holt','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100605,'Hiram P. Flynn','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100611,'Keith J. Hurley','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100616,'Elijah L. Wells','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100618,'Tyrone M. Keith','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100622,'Abel D. Stuart','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100631,'Jenette C. Perkins','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100639,'Ivana B. Combs','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100647,'Hiram V. Booth','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100649,'Rachel X. Kelley','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100657,'Thor E. Montgomery','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100661,'Kennedy G. Jacobs','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100669,'Charissa S. Underwood','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100676,'Jesse P. Powell','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100679,'Vaughan X. Benjamin','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100681,'Todd M. Abbott','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100682,'Judith T. Grant','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100689,'Rhiannon F. Mcdaniel','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100692,'Elizabeth F. Murphy','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100699,'Kim T. Ellison','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100703,'Knox O. Soto','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100704,'Inga B. Hooper','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100711,'Jordan W. Landry','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100713,'Jemima F. Britt','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100721,'Rhonda S. Marks','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100724,'Matthew I. Levy','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100730,'Dara Y. Rosario','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100734,'Freya R. Knight','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100736,'Lesley I. Weeks','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100737,'Cullen N. Knox','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100740,'Rudyard C. Hensley','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100741,'Fleur P. Cochran','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100742,'Raja D. Logan','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100749,'Russell F. Jacobson','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100757,'Dale T. House','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100758,'Peter C. Morales','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100763,'Nero W. Gates','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100764,'Nina H. Reyes','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100771,'Lee C. Lindsey','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100772,'Declan C. Dickerson','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100779,'Russell K. Bean','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100786,'Colt T. Wilkins','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100790,'Ginger I. Camacho','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100794,'Sasha M. Manning','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100796,'Forrest U. Shepherd','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100804,'Lawrence E. Gallegos','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100812,'Gabriel F. Cherry','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100815,'Callum D. Kane','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100820,'Daniel E. Williamson','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100827,'Hamilton P. Rivera','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100828,'Anastasia L. Willis','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100830,'Julian Z. Jensen','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100834,'Cathleen D. Guy','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100836,'Elaine V. Barton','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100842,'Sydnee E. Gregory','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100848,'Lois P. Leon','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100857,'Melinda U. Mayo','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100865,'Richard V. Kirby','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100867,'Arthur Z. Alvarado','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100868,'Dale L. Duffy','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100870,'Abel T. Merrill','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100873,'Jin P. Wagner','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100877,'Alyssa K. Sharp','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100884,'Hilary A. Edwards','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100892,'Sharon P. Berry','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100901,'Bianca W. Craig','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100910,'Hilel I. Mckee','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100919,'Candice B. Zamora','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100922,'Cody C. Haynes','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100924,'Sylvester K. Mcbride','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100931,'Aiko L. Albert','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100932,'Shelly X. Hyde','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100933,'Boris O. Chapman','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100941,'Sebastian G. Reeves','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100946,'Maris T. Schultz','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100952,'Fleur X. Vance','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100961,'Yoshio A. Webb','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100970,'Solomon Z. WestIndividuals','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100978,'Byron V. Ward','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100987,'Linda O. Donaldson','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (100995,'Hayfa W. Nelson','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101001,'Mechelle K. Bright','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101002,'Denise Q. Higgins','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101008,'Maya X. England','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101016,'Jakeem W. Bray','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101020,'April S. Harrell','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101026,'Randall P. Pollard','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101030,'Doris L. Cummings','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101039,'Jeremy A. Kerr','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101043,'Zia Y. Ramos','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101045,'Marcia M. Hopper','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101048,'Eagan C. Mclaughlin','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101054,'Lynn T. Fitzpatrick','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101055,'Adam B. Sutton','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101056,'Hu H. Martinez','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101061,'Demetria J. Byrd','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101067,'Beau N. Rosales','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101070,'Regina Y. Whitley','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101076,'Katell J. Prince','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101081,'Wilma Y. Mcfadden','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101087,'Maggy A. Newton','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101093,'Emery W. Stafford','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101094,'Rinah N. Huff','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101102,'Liberty Z. Dalton','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101104,'Mary G. Jordan','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101108,'Driscoll O. Foreman','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101116,'Sophia H. Barr','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101123,'Sierra M. Vaughan','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101132,'Conan V. Bright','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101136,'Forrest W. Hodges','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101140,'Michael J. Rowland','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101142,'Josiah H. Reynolds','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101150,'Xantha D. Poole','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101152,'Rafael Q. Ballard','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101153,'Desiree Q. Macias','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101162,'Rhoda D. Camacho','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101167,'Bree T. Mcclain','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101168,'Clinton Q. Harper','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101176,'Darrel Y. Sellers','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101181,'Lionel J. Mccray','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101186,'Dane Y. Delgado','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101193,'Alyssa W. Mcfarland','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101201,'Warren D. Soto','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101207,'Leigh Z. Caldwell','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101214,'Clarke M. Porter','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101217,'Hammett X. Eaton','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101224,'Petra V. Livingston','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101226,'Tatyana B. Ortiz','Individuals');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101231,'Optum','Company');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101240,'Nielsen','Company');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101242,'Video Research Ltd.','Company');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101248,'Equifax','Company');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101251,'Kantar','Company');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101253,'QuintilesIMS','Company');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101259,'Ipsos','Company');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101263,'Gartner','Company');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101266,'GfK','Company');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101268,'Verisk Analytics','Company');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101270,'IRI','Company');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101273,'Acxiom Corp.','Company');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101280,'Tableau Software','Company');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101285,'Experian Consumer insight','Company');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101289,'Westat, Inc.','Company');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101294,'Rocket Fuel','Company');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101301,'Wood Mackenzie','Company');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101303,'Dunnhumby','Company');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101307,'Intage Holdings','Company');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101315,'Harte-Hanks Marketing','Company');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101323,'iDC','Company');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101332,'Informa Financial Intelligence','Company');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101340,'NPD Group','Company');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101343,'J.D. Power','Company');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101351,'comScore','Company');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101352,'Macromill','Company');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101354,'Simon-Kucher & Partners','Company');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101358,'Qualtrics','Company');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101363,'Gallup','Company');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101369,'Research Now Group, Inc','Company');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101371,'ICF International','Company');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101372,'Information Services Group','Company');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101374,'Forrester Research','Company');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101383,'SurveyMonkey','Company');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101388,'Toluna','Company');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101397,'DRG (Decision Resources Group)','Company');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101399,'MaritzCX','Company');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101400,'Survey Sampling International','Company');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101404,'Abt SRBI','Company');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101412,'LRW (Lieberman Research Worldwide)','Company');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101418,'GlobalData Plc','Company');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101425,'YouGov','Company');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101434,'Leger','Company');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101438,'Mediametrie','Company');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101445,'ORC International','Company');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101447,'Creston','Company');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101455,'National Research Corp','Company');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101456,'FocusVision','Company');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101465,'PRS IN VIVO','Company');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101466,'NRC health','Company');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101474,'Cello health','Company');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101475,'Teradata UK','Company');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101482,'Euromonitor','Company');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101490,'Confirmit','Company');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101498,'Vision Critical','Company');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101505,'C Space','Company');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101513,'Mintel Group','Company');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101517,'Google Analytics 360','Company');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101518,'Blueocean Market Intelligence','Company');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101527,'Burke, Inc.','Company');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101531,'Periscope by McKinsey','Company');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101539,'Ebiquity','Company');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101543,'Schlesinger Associates','Company');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101546,'Medallia','Company');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101554,'Convergys Analytics','Company');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101557,'Market Strategies International','Company');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101558,'MarketCast','Company');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101563,'Morpace, Inc.','Company');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101571,'Nepa AB','Company');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101576,'Market Force','Company');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101579,'Service Management Group (SMG)','Company');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101585,'Idea Couture','Company');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101587,'LRA by Deloitte','Company');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101595,'Focus Pointe Global','Company');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101602,'Directions Research','Company');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101604,'Precise Media Monitoring','Company');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101611,'Hanover Research','Company');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101618,'MARU / Matchbox','Company');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101627,'Environics','Company');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101629,'De La Riva Group','Company');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101635,'SKIM','Company');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101642,'Phoenix Marketing International','Company');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101647,'MarketVision Research','Company');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101649,'Radius Global Market Research','Company');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101653,'Simmons Research','Company');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101655,'NatCen','Company');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101657,'Brainjuicer','Company');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101659,'Kelton','Company');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101666,'Fors Marsh Group','Company');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101671,'Provokers','Company');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101675,'Isobar Marketing Intelligence','Company');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101677,'Insites Consulting','Company');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101684,'Hall & Partners','Company');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101687,'SSRS','Company');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101692,'Decision Analyst','Company');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101699,'Twitter','Company');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101704,'Double Helix','Company');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101710,'The Link Group','Company');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101717,'Flamingo Research','Company');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101722,'MMR Research Worldwide','Company');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101723,'Zappistore','Company');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101729,'20/20 Research','Company');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101733,'Forethought Research','Company');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101742,'Gongos','Company');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101745,'Stylus','Company');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101749,'Acturus','Company');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101755,'Lucid','Company');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101760,'The Research Partnership','Company');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101763,'NAXIoN','Company');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101769,'KS&R','Company');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101772,'QuestionPro','Company');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101781,'Bellomy Research','Company');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101790,'Chadwick Martin Bailey','Company');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101797,'Illuminas','Company');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101803,'Frost & Sullivan','Company');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101811,'Hypothesis Group','Company');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101819,'Future Thinking','Company');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101827,'RTi Research','Company');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101833,'Azure Knowledge','Company');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101841,'Cint','Company');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101849,'Luth','Company');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101853,'Netbase','Company');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101856,'WorldOne Research','Company');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101865,'Hay Group Insight','Company');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101867,'Amazon Mechanical Turk','Company');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101874,'Hotspex Inc','Company');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101876,'Populus group','Company');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101877,'BDRC Continental','Company');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101881,'Defaqto','Company');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101885,'SurveyGizmo','Company');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101889,'Eolas International','Company');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101893,'Incite Marketing Planning','Company');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101894,'Markit Economics','Company');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101899,'Adelphi international Research','Company');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101906,'Q Research Solutions','Company');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101913,'Datamonitor','Company');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101919,'InCrowd Inc','Company');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101927,'Firefish','Company');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101928,'Realeyes','Company');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101932,'MSW ARS','Company');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101938,'Business Research group','Company');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101945,'Avention UK','Company');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101953,'Quadrangle','Company');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101960,'Marketing sciences Unlimited','Company');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101963,'Strategy Analytics','Company');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101965,'Brandtrust','Company');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101974,'iCM Research Unlimited','Company');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101977,'2CV','Company');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101981,'The Planning shop international','Company');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101987,'Ameritest','Company');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101992,'Chinese Academy of Sciences (CAS)','Institute');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (101997,'Peking University (PKU)','Institute');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (102005,'Nanjing University (NJU)','Institute');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (102007,'University of Science and Technology of China (USTC)','Institute');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (102012,'Nankai University (NKU)','Institute');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (102014,'Zhejiang University (ZJU)','Institute');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (102016,'Fudan University','Institute');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (102022,'Tsinghua University (TH)','Institute');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (102028,'Soochow University','Institute');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (102030,'University of Oxford','Institute');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (102038,'Institute for Basic Science (IBS)','Institute');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (102045,'Stanford University','Institute');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (102049,'East China Normal University (ECNU)','Institute');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (102056,'Hunan University (HNU)','Institute');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (102062,'Sichuan University (SCU)','Institute');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (102070,'Indian Institutes of Technology (IITs)','Institute');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (102075,'Xiamen University (XMU)','Institute');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (102078,'The University of Manchester (UoM)','Institute');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (102079,'King Abdullah University of Science and Technology (KAUST)','Institute');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (102086,'Nanyang Technological University (NTU)','Institute');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (102095,'Chongqing University (CQU)','Institute');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (102099,'Swiss Federal Institute of Technology in Lausanne (EPFL)','Institute');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (102108,'Imperial College London (ICL)','Institute');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (102112,'Indian Institute of Science Education and Research (IISER)','Institute');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (102121,'Southwest University (SWU)','Institute');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (102125,'Technion-Israel Institute of Technology (IIT)','Institute');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (102126,'Tianjin University (TJU)','Institute');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (102135,'Wuhan University (WHU)','Institute');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (102138,'Baylor College of Medicine (BCM)','Institute');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (102140,'Helmholtz Association of German Research Centres','Institute');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (102146,'North Carolina State University (NCSU)','Institute');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (102149,'Stockholm University','Institute');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (102155,'University of Chinese Academy of Sciences (UCAS)','Institute');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (102162,'Sun Yat-sen University (SYSU)','Institute');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (102165,'Jilin University (JLU)','Institute');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (102170,'Lanzhou University (LZU)','Institute');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (102172,'McGill University','Institute');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (102180,'East China University of Science and Technology (ECUST)','Institute');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (102189,'Hong Kong University of Science and Technology (HKUST)','Institute');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (102192,'South China University of Technology (SCUT)','Institute');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (102194,'University of Southampton (Soton)','Institute');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (102199,'Xi''an Jiaotong University (XJTU)','Institute');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (102205,'Harbin Institute of Technology (HIT)','Institute');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (102213,'University College London (UCL)','Institute');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (102215,'Changzhou University (CZU)','Institute');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (102219,'Huazhong University of Science and Technology (HUST)','Institute');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (102225,'King''s College London (KCL)','Institute');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (102228,'Swiss Federal Institute of Technology Zurich (ETH Zurich)','Institute');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (102231,'Italian Institute of Technology (IIT)','Institute');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (102234,'Ulsan National Institute of Science and Technology (UNIST)','Institute');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (102243,'Oak Ridge National Laboratory (ORNL)','Institute');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (102247,'University of New South Wales (UNSW)','Institute');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (102252,'Beijing Normal University (BNU)','Institute');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (102260,'Central South University (CSU)','Institute');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (102269,'Shaanxi Normal University (SNNU)','Institute');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (102276,'Shandong Normal University (SDNU)','Institute');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (102285,'The Rockefeller University','Institute');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (102293,'The University of Queensland (UQ)','Institute');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (102294,'University of Regensburg (UR)','Institute');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (102295,'Tata Institute of Fundamental Research (TIFR)','Institute');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (102304,'Beijing University of Chemical Technology (BUCT)','Institute');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (102311,'South University of Science and Technology of China (SUSTC)','Institute');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (102318,'University of Sussex (US)','Institute');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (102320,'Zhengzhou University (ZZU)','Institute');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (102323,'University of Zurich (UZH)','Institute');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (102326,'Indian Institute of Science (IISc)','Institute');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (102330,'Perimeter Institute for Theoretical Physics (PI)','Institute');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (102335,'University of Pennsylvania (Penn)','Institute');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (102339,'Jagiellonian University (UJ)','Institute');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (102346,'Council of Scientific and Industrial Research (CSIR)','Institute');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (102355,'University of Münster (WWU)','Institute');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (102364,'Beihang University (BUAA)','Institute');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (102365,'Lund University (LU)','Institute');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (102372,'University of Bath','Institute');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (102381,'National Institute for Health and Medical Research (INSERM)','Institute');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (102382,'University of Erlangen-Nuremberg (FAU)','Institute');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (102384,'University of Copenhagen (UCPH)','Institute');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (102385,'Tongji University','Institute');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (102387,'U.S. Geological Survey (USGS)','Institute');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (102393,'University of Michigan (U-M)','Institute');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (102395,'São Paulo State University (UNESP)','Institute');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (102402,'University of Basel (UB)','Institute');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (102405,'University of Würzburg','Institute');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (102411,'University of Girona (UdG)','Institute');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (102414,'Heidelberg University (Uni Heidelberg)','Institute');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (102416,'University of Leeds','Institute');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (102425,'Pierre and Marie Curie University (UPMC) - Paris 6','Institute');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (102428,'Southeast University (SEU)','Institute');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (102434,'Leibniz Association','Institute');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (102443,'University of Nebraska-Lincoln (UNL)','Institute');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (102447,'Saint Petersburg State University (SPbGU)','Institute');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (102451,'National Aeronautics and Space Administration (NASA)','Institute');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (102452,'Umeå University (UMU)','Institute');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (102456,'Curtin University','Institute');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (102463,'University of Turin (UNITO)','Institute');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (102466,'University of Warsaw (UW)','Institute');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (102468,'University of Stuttgart','Institute');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (102473,'Nanjing University of Science and Technology (NUST)','Institute');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (102475,'Lawrence Berkeley National Laboratory (LBNL)','Institute');
INSERT INTO Patentees(Patentee_ID,Patentee_Name,Patentee_Category) VALUES (102480,'Nanjing Normal University (NNU)','Institute');
